### ISSUE TITLE
Cannot bundle Node. js built-in "node: crypto"

### ISSUE THREAD

**Issue by hckhanh** [upstash/workflow-js#24]
I cannot use workflow for astro to build a pages project for cloudflare

![image](https://github.com/user-attachments/assets/ae8c2fc7-e2be-4143-91ed-6088ca58da8e)

**Comment by hckhanh** [comment]
It still worked in 0.1.2, but 0.1.4

![image](https://github.com/user-attachments/assets/39c6e118-d9a5-4393-8eca-71e6135efafd)

**Comment by CahidArda** [comment]
Thanks for the report @hckhanh,

we use crypto to generate random strings and recently updated crypto import to make workflow work in Node 18, but it looks like it breaks in other cases.

we will look into replacing crypto with our own random number generator like [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random).
